### ISSUE TITLE
Error: Incompatible library version

### ISSUE THREAD

**Issue by vdesabou** [ramiroaraujo/alfred-transmit-workflow#2]
Hi Ramiro,

I have this issue on my MacbookPro (10.9.1):

```
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/vincent/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.2FBE92E9-D52E-493A-9C17-F231F354EA86/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: /Users/ramiroaraujo/Development/Projects/alfred-transmit-workflow/workflow/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ports/x86_64-apple-darwin13.0.0/libxml2/2.8.0/lib/libxml2.2.dylib (LoadError)
  Referenced from: /Users/vincent/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.2FBE92E9-D52E-493A-9C17-F231F354EA86/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 11.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /Users/vincent/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.2FBE92E9-D52E-493A-9C17-F231F354EA86/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/lib/nokogiri/nokogiri.bundle
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/vincent/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.2FBE92E9-D52E-493A-9C17-F231F354EA86/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/lib/nokogiri.rb:28:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./main.rb:6:in `<main>'
```

Any idea what's going on here?

Thanks!

**Comment by ramiroaraujo** [comment]
hmm, in the rush I may have exported the workflow incorrectly. My dev version works fine, I'll check. Thanks!

**Comment by ramiroaraujo** [comment]
Actually, it was a packaging thing with the nokogiri gem, and some asumptions about libraries available in OSX... I changed the library to xml-simple, since its much... simpler :)

I'm closing this issue since it's no longer relevant; your error is involved with the nokogiri gem. I hope this change fixes it.
